metric1 <- c(7,7,4,7,7,7)
metric2 <- c(7,7,6,7,7,7)
metric3 <- c(7,7,5,7,7,7)
metric4 <- c(7,7,4,7,7,7)
metric5 <- c(7,7,4,7,6,7)
metric6 <- c(7,7,7,7,7,6)
metric7 <- c(7,7,7,7,7,6)
metric8 <- c(7,7,4,7,6,5)
metric9 <- c(7,4,4,7,7,4)
metric10 <- c(7,4,7,7,5,4)
metric11 <- c(7,7,7,7,7,7)
metric12 <- c(7,7,7,7,7,7)
metric13 <- c(7,7,7,7,7,7)
metric14 <- c(7,7,7,6,7,7)
metric15 <- c(7,7,7,7,7,7)
metric16 <- c(7,7,7,7,7,7)
metric17 <- c(7,7,7,7,6,7)
metric18 <- c(7,7,7,7,7,7)

metric1_mean <- mean(metric1)
metric2_mean <- mean(metric2)
metric3_mean <- mean(metric3)
metric4_mean <- mean(metric4)
metric5_mean <- mean(metric5)
metric6_mean <- mean(metric6)
metric7_mean <- mean(metric7)
metric8_mean <- mean(metric8)
metric9_mean <- mean(metric9)
metric10_mean <- mean(metric10)
metric11_mean <- mean(metric11)
metric12_mean <- mean(metric12)
metric13_mean <- mean(metric13)
metric14_mean <- mean(metric14)
metric15_mean <- mean(metric15)
metric16_mean <- mean(metric16)
metric17_mean <- mean(metric17)
metric18_mean <- mean(metric18)

cat("The mean of the metric 1 is:", metric1_mean, "\n")
cat("The mean of the metric 2 is:", metric2_mean, "\n")
cat("The mean of the metric 3 is:", metric3_mean, "\n")
cat("The mean of the metric 4 is:", metric4_mean, "\n")
cat("The mean of the metric 5 is:", metric5_mean, "\n")
cat("The mean of the metric 6 is:", metric6_mean, "\n")
cat("The mean of the metric 7 is:", metric7_mean, "\n")
cat("The mean of the metric 8 is:", metric8_mean, "\n")
cat("The mean of the metric 9 is:", metric9_mean, "\n")
cat("The mean of the metric 10 is:", metric10_mean, "\n")
cat("The mean of the metric 11 is:", metric11_mean, "\n")
cat("The mean of the metric 12 is:", metric12_mean, "\n")
cat("The mean of the metric 13 is:", metric13_mean, "\n")
cat("The mean of the metric 14 is:", metric14_mean, "\n")
cat("The mean of the metric 15 is:", metric15_mean, "\n")
cat("The mean of the metric 16 is:", metric16_mean, "\n")
cat("The mean of the metric 17 is:", metric17_mean, "\n")
cat("The mean of the metric 18 is:", metric18_mean, "\n")

data <- c(metric1_mean,metric2_mean,metric3_mean,metric4_mean,metric5_mean,metric6_mean,metric7_mean,metric8_mean,metric9_mean,metric10_mean,metric11_mean,metric12_mean,metric13_mean,metric14_mean,metric15_mean,metric16_mean,metric17_mean,metric18_mean)
labels <- c("Satisfied with how easy it is to use", "Simple to use", "Effectively complete work", "Complete work quickly", "Efficiently complete work", "Comfortable using", "Easy to learn to use", "Became productive quickly", "Gives error messages","The information is clear", "Easy to find the information", "Information provided is easy to understand","Information is effective", "Organization of information is clear", "Interface is pleasant","Like using the interface", "Has all functions and capabilities", "Overall satisfied")

barplot(data, names.arg = labels, col = "skyblue", main = "Averages for CSU Survey Results per Metric", ylab = "Mean", xlab = "Metrics", cex.names = 0.5)
text(x = bp, y = par("usr")[3] - 1, labels = labels, srt = 45, adj = 1, xpd = TRUE)

